config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: %i[show new create edit update destroy] do
    resources :stock_product_destinations, only: %i[create]
  end
  resources :suppliers, only: %i[index show new create edit update destroy]
  resources :product_models, only: %i[index show new create]
  resources :orders, only: %i[new create show index edit update edit update] do
    resources :order_items, only: %i[new create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end
  namespace :api do 
    namespace :v1 do 
      resources :warehouses, only: %i[show index new create]
    end
  end
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier
  has_many :order_items
  has_many :orders, through: :order_items
  validates :name, :sku, presence: true
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  def index
    @product_models = ProductModel.all
  end

  def new
    @product_model = ProductModel.new
    @suppliers = Supplier.all
  end

  def create
    @product_model = ProductModel.new(product_model_params)
    if @product_model.save
      flash[:notice] = 'Modelo de produto cadastrado com sucesso.'
      redirect_to @product_model
    else
      @suppliers = Supplier.all
      flash.now[:notice] = 'Não foi possível cadastrar o produto.'
      render 'new'
    end
  end

  def show
    @product_model = ProductModel.find(params[:id])
  end

  private

  def product_model_params
    params.require(:product_model).permit(:name, :weight, :height, :width, :depth, :sku, :supplier_id)
  end
end

app/views/product_models/index.html.erb
<h1>Modelos de Produtos</h1>

<%= link_to 'Cadastrar Novo Produto', new_product_model_path %>

<% if @product_models.any?  %>

  <% @product_models.each do |pm|  %>
    <div>
      <strong>Produto</strong> <%= link_to pm.name, product_model_path(pm.id) %>
      <strong>SKU</strong> <%= pm.sku  %>
      <strong>Forncedor</strong> <%= pm.supplier.brand_name %>
    </div>
  <% end %>
<% else %>
   <p>Nenhum modelo de produto cadastrado.<p>

<% end %>

app/views/product_models/new.html.erb
<h1>Cadastar Modelo de Produto</h1>

<%= form_with(model: @product_model) do |f|  %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name  %>
  </div>
  <div>
    <%= f.label :weight %>
    <%= f.number_field :weight  %>
  </div>
  <div>
    <%= f.label :width %>
    <%= f.number_field :width  %>
  </div>
  <div>
    <%= f.label :height %>
    <%= f.number_field :height  %>
  </div>
  <div>
    <%= f.label :depth %>
    <%= f.number_field :depth  %>
  </div>
  <div>
    <%= f.label :sku %>
    <%= f.text_field :sku  %>
  </div>
  <div>
    <%= f.label :supplier_id %>
    <%= f.collection_select :supplier_id, @suppliers, :id, :brand_name %>
  </div>
  <div>
    <%= f.submit 'Salvar' %>
  </div>
<% end %>

app/views/product_models/show.html.erb
<h1><%= @product_model.name  %></h1>
<div>
  <strong>Fornecedor:</strong> <%= @product_model.supplier.brand_name %>
</div>
<div>
  <strong>SKU:</strong> <%= @product_model.sku %>
</div>
<div>
  <strong>Dimensão:</strong> <%= @product_model.height %>cm x 
  <%= @product_model.width %>cm x <%= @product_model.depth %>cm
</div>
<div>
  <strong>Peso:</strong> <%= @product_model.weight %>g
</div>

<%= link_to 'Voltar', product_models_path %>