config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: %i[show new create edit update destroy] do
    resources :stock_product_destinations, only: %i[create]
  end
  resources :suppliers, only: %i[index show new create edit update destroy]
  resources :product_models, only: %i[index show new create]
  resources :orders, only: %i[new create show index edit update edit update] do
    resources :order_items, only: %i[new create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end
  namespace :api do 
    namespace :v1 do 
      resources :warehouses, only: %i[show index new create]
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :warehouse
  belongs_to :user
  belongs_to :supplier
  has_many :order_items
  has_many :product_models, through: :order_items

  enum status: { pending: 0, delivered: 5, canceled: 9 }

  validates :code, :estimated_delivery_date, presence: true
  validate :estimated_delivery_date_cannot_be_in_the_pass

  before_validation :generate_code, on: :create

  def generate_code
    self.code = SecureRandom.alphanumeric(8).upcase
  end

  def estimated_delivery_date_cannot_be_in_the_pass
    return unless estimated_delivery_date.present? && estimated_delivery_date <= Date.today

    errors.add(:estimated_delivery_date, 'A data não pode ser inferior a data atual')
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order_and_check_user, only: %i[show edit update delivered canceled]

  def index
    @orders = current_user.orders
  end

  def new
    @order = Order.new
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    if @order.save!
      flash[:notice] = 'Pedido registrado com sucesso.'
      redirect_to @order
    else
      @warehouses = Warehouse.all
      @suppliers = Supplier.all
      flash.now[:notice] = 'Não foi possível salvar o pedido.'
      render 'new'
    end
  end

  def show; end

  def search
    @code = params['query']
    @orders = Order.where('code LIKE ?', "%#{@code}%")
  end

  def edit
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
  end

  def update
    @order = Order.update(order_params)
    redirect_to @order, notice: 'Pedido atualizado com sucesso'
  end

  def delivered
    @order.delivered!
    @order.order_items.each do |item|
      item.quantity.times do
        StockProduct.create!(
          order: @order,
          product_model: item.product_model,
          warehouse: @order.warehouse
        )
      end
    end
    redirect_to @order
  end

  def canceled
    @order.canceled!
    redirect_to @order
  end

  private

  def order_params
    params.require(:order).permit(:warehouse_id, :supplier_id, :estimated_delivery_date)
  end

  def set_order_and_check_user
    @order = Order.find(params[:id])
    return unless @order.user != current_user

    redirect_to root_path, notice: 'Você não tem acesso ao este pedido.'
  end
end

app/views/orders/_form.html.erb
<%= form_with(model: @order) do |f| %>
  <div>
    <%= f.label :warehouse_id %>
    <%= f.collection_select :warehouse_id, @warehouses, :id, :full_description %>
  </div>
  <div>
    <%= f.label :supplier_id %>
    <%= f.collection_select :supplier_id, @suppliers, :id, :corporate_name %>
  </div>
  <div>
    <%= f.label :estimated_delivery_date %>
    <%= f.date_field :estimated_delivery_date %>
  </div>
  <%= f.submit 'Gravar' %>
<% end %>

app/views/orders/_order.html.erb
  <div>
    <strong><%= Order.human_attribute_name(:code)  %>: </strong>
    <%= link_to order.code, order %>
  </div>

  <div>
  <strong><%= Order.human_attribute_name(:warehouse_id)  %>: </strong> 
    <%= order.warehouse.full_description %>
  </div>
  <div>
  <strong><%= Order.human_attribute_name(:supplier_id)  %>: </strong> 
    <%= order.supplier.corporate_name %>
  </div>
   <div>
  <strong><%= Order.human_attribute_name(:status)  %>: </strong> 
    <%= I18n.translate(order.status)%>
  </div>

app/views/orders/edit.html.erb
<%= render 'form' %>

app/views/orders/index.html.erb
<h2>Meus Pedidos:</h2>
<div>
<% @orders.each do |order| %>
  <div>
  <strong>1 pedido encontrado</strong>
  </div>
 <%= render order %>
<% end %>
</div>

app/views/orders/new.html.erb
<h1>Registro de Pedido</h1>


<%= render 'form'  %>

app/views/orders/search.html.erb
<h1>Resultado da Busca por: <%= @code %></h1> 

  <p><%= @orders.count  %> <%=  Order.model_name.human(count: @orders.count).downcase %> <%= I18n.translate(:found, count: @orders.count)  %></p>

<% @orders.each do |order| %>

  <%= render order %>
<% end %>

app/views/orders/show.html.erb
<h2>Detalhes do Pedido</h2>
<h3><%= Order.model_name.human %><%= @order.code  %></h3>
<div>
  <strong><%= Order.human_attribute_name(:warehouse_id)  %>:</strong> <%= @order.warehouse.full_description %>
</div>
<div>
  <strong><%= Order.human_attribute_name(:supplier_id)  %>:</strong> <%= @order.supplier.corporate_name %>
</div>
<div>
  <strong><%= Order.human_attribute_name(:user_id)  %>:</strong> <%= @order.user.description %>
</div>
<div>
  <strong><%= Order.human_attribute_name(:estimated_delivery_date)  %>:</strong> <%= I18n.localize(@order.estimated_delivery_date) %>
</div>
<div>
  <strong><%= Order.human_attribute_name(:status) %>:</strong> <%= I18n.translate(@order.status) %>
</div>
<h2>Itens do Pedido</h2>
<%= link_to 'Adicionar Item',  new_order_order_item_path(order_id: @order.id) %>
<% @order.order_items.each do |item| %>
  <%= item.quantity %> x <%= item.product_model.name %>
<% end %>


<% if @order.pending? %>
  <%= button_to 'Entregue', delivered_order_path(@order.id) %>
  <%= button_to 'Cancelado', canceled_order_path(@order.id) %>
<% end %>
<%= link_to 'Editar', edit_order_path(@order.id) %>