config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: %i[show new create edit update destroy] do
    resources :stock_product_destinations, only: %i[create]
  end
  resources :suppliers, only: %i[index show new create edit update destroy]
  resources :product_models, only: %i[index show new create]
  resources :orders, only: %i[new create show index edit update edit update] do
    resources :order_items, only: %i[new create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end
  namespace :api do 
    namespace :v1 do 
      resources :warehouses, only: %i[show index new create]
    end
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :product_models
  validates :corporate_name, :brand_name, :registration_number, :full_address, :zip, :city, :state, :email,
            presence: true
  validates :corporate_name, :registration_number, uniqueness: true
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  # before_action :set_supplier, only: [:show, :new, :create]
  def index
    @suppliers = Supplier.all
  end

  def show
    @supplier = Supplier.find(params[:id])
  end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)
    if @supplier.save
      flash[:notice] = 'Fornecedor cadastrado com sucesso.'
      redirect_to supplier_path(@supplier.id)
    else
      flash.now[:notice] = 'Não foi possível cadastrar fornecedor.'
      render 'new'
    end
  end

  def edit
    @supplier = Supplier.find(params[:id])
  end

  def update
    @supplier = Supplier.find(params[:id])
    if @supplier.update(supplier_params)
      flash[:notice] = 'Fornecedor atualizado com sucesso.'
      redirect_to supplier_path(@supplier.id)
    else
      flash.now[:notice] = 'Não foi possível atualizar dados do forcenedor.'
      render 'edit'
    end
  end

  private

  def set_supplier
    @supplier = Supplier.find(params[:id])
  end

  def supplier_params
    params.require(:supplier).permit(:corporate_name, :brand_name, :registration_number, :full_address, :zip, :city,
                                     :state, :email)
  end
end

app/views/suppliers/_form.html.erb
<%= form_with(model: @supplier) do |f|  %>
  <div>
    <%= f.label :corporate_name %>
    <%= f.text_field :corporate_name %>
  </div>
  <div>
    <%= f.label :brand_name  %>
    <%= f.text_field :brand_name %>
  </div>
  <div>
    <%= f.label :registration_number  %>
    <%= f.text_field :registration_number%>
  </div>
  <div>
    <%= f.label :full_address %>
    <%= f.text_field :full_address %>
  </div>
  <div>
    <%= f.label :zip%>
    <%= f.text_field :zip %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city%>
  </div>
  <div>
    <%= f.label :state %>
    <%= f.text_field :state%>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email%>
  </div>

  <div>
    <%= f.submit 'Salvar' %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<h2>Editar dados do fornecedor</h2>

<% if(@supplier.errors.any?)%>
  <% @supplier.errors.full_messages.each do |msg| %>
    <li><%= msg %></li> 
  <% end %>
<% end %>

<%= render 'form' %>

app/views/suppliers/index.html.erb
<h2>Fornecedores cadastrados</h1>
<strong><%= link_to 'Cadastrar Fornecedor', new_supplier_path %></strong>
<% if @suppliers.any? %>
  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Cidade</th>
      </tr>
    </thead>
    <tbody>
      <% @suppliers.each do |supplier| %>
        <tr>
          <div>
            <td><%= link_to supplier.brand_name, supplier_path(supplier.id)%></td>
            <td><%= supplier.city %>-<%= supplier.state  %></td>
          </div>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else%>
  <p>Não existem fornecedores cadastrados.</p>
<% end %>

app/views/suppliers/new.html.erb
<h2>Cadastrar novo fornecedor</h2>

<% if(@supplier.errors.any?)%>
  <% @supplier.errors.full_messages.each do |msg| %>
    <li><%= msg %></li> 
  <% end %>
<% end %>

<%= render 'form' %>

app/views/suppliers/show.html.erb
<h2>Fornecedor: <%= @supplier.brand_name  %></h2>
<h3><%= @supplier.corporate_name %></h3>

<dl>
  <dt>Número de registro:</dt> 
  <dd><%= @supplier.registration_number  %></dd>
  <dt>Endereço:</dt>  
  <dd><%= @supplier.full_address  %></dd>
  <dt>CEP:</dt> 
  <dd><%= @supplier.zip  %></dd>
  <dt>Cidade:</dt> 
  <dd><%= @supplier.city  %></dd>
  <dt>Estado:</dt> 
  <dd><%= @supplier.state  %></dd>
  <dt>E-mail:</dt> 
  <dd><%= @supplier.email  %></dd>

</dl>
<div>
  <%= link_to 'Editar', edit_supplier_path %>
</div>
<div>
  <%= link_to 'Voltar', root_path %>
</div>